name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_NAME_IMAGE: docker-graphql
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major-pattern: "major:"
        minur-pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
      
    - name: Docker Login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            
    
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t $DOCKER_USER/$DOCKER_NAME_IMAGE:$NEW_VERSION .
        docker build -t $DOCKER_USER/$DOCKER_NAME_IMAGE:latest .
        
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push $DOCKER_USER/$DOCKER_NAME_IMAGE:$NEW_VERSION
        docker push $DOCKER_USER/$DOCKER_NAME_IMAGE:latest
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
